import { StyleSheet } from 'react-native';
import {
    responsiveWidth,
    responsiveHeight,
} from 'react-native-responsive-dimensions';
const groomingaboutstyles = StyleSheet.create({
    container: {
        top:responsiveHeight(2),
        gap: responsiveHeight(2),
        width: responsiveWidth(100),
        height: responsiveHeight(100),
        backgroundColor: '#FFFFFF',
    },
    containerchild: {
        width: responsiveWidth(100),
        padding: responsiveWidth(4),
        flexDirection: 'row',
        justifyContent: 'space-between',
        top: responsiveHeight(4),
        paddingHorizontal: responsiveHeight(2.5),
    },
    containerfirstsubchild: {
        flexDirection: 'row',
        gap: responsiveWidth(1),
    },
    downArrowIcon: {
        tintColor: '#000000',
        top: responsiveHeight(0.25),
    },
    leftarrowicon: {
        tintColor: '#000000',
        top: responsiveHeight(0.5),
    },
    locationtext: {
        flexDirection: 'row',
        gap: responsiveWidth(1),
        top: responsiveHeight(0.5),
    },
    locationtextColor: { color: '#000000' },
    groomingText: {
        color: '#000000',
        fontSize: 20,
        fontWeight: '500',
        fontFamily: '',
    },

    containerthirdsubchild: {
        paddingHorizontal: responsiveWidth(0.3),
        top: responsiveHeight(0.4),
    },
    shadow: {
        flexDirection: 'row',
        paddingHorizontal: responsiveHeight(2),
        paddingVertical: responsiveHeight(2),
        gap: responsiveWidth(2),
        width: responsiveWidth(90),
        height: responsiveHeight(14),
        backgroundColor: '#FFFFFF',
    },
    userimage: {
        width: responsiveWidth(20),
        height: responsiveWidth(20),
        borderRadius: responsiveWidth(20),
    },
    onsitetext: {
        paddingHorizontal: responsiveWidth(5),
        paddingTop: responsiveHeight(5),
        paddingBottom: responsiveHeight(1),
        color: '#AAAAAA',
        fontSize: 16,
        fontWeight: '600',
        lineHeight: 20,
    },
    homeservicetext: {
        paddingHorizontal: responsiveWidth(12),
        paddingTop: responsiveHeight(5),
        paddingBottom: responsiveHeight(1),
        color: '#58B9D0',
        fontSize: 16,
        fontWeight: '600',
        lineHeight: 20,
        width: responsiveWidth(50),
        borderBottomWidth: responsiveWidth(0.5),
        borderColor: '#58B9D0',
    },
    gap: { gap: responsiveHeight(1) },
    userTextWidth: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: responsiveWidth(68),
    },
    userTextgap: {
        flexDirection: 'row',
        gap: responsiveWidth(2.5),
    },
    textSize: { fontSize: 16, fontWeight: '800' },
    borderRadius: {
        width: responsiveWidth(20.6),
        height: responsiveHeight(2.8),
        borderRadius: responsiveWidth(4),
        borderWidth: 1,
        borderColor: '#58B9D0',
        alignItems: 'center',
    },
    celebrityText: {
        color: '#58B9D0',
        marginTop: responsiveHeight(0.1),
    },

    ratingGap: {
        flexDirection: 'row',
        gap: responsiveWidth(1),
    },
    ratingHeight: { top: responsiveHeight(0.3) },
    ratePointSize: {
        color: '#848484',
        fontSize: 16,
        fontWeight: '400',
    },
    setIconTextGap: {
        flexDirection: 'row',
        gap: responsiveWidth(2),
    },
    setImageIconPosition: { top: responsiveHeight(0.3) },
    setTextSize: {
        fontSize: responsiveHeight(1.5),
        lineHeight: responsiveHeight(2),
        letterSpacing: responsiveWidth(0),
        color: '#383838',
    },
    setDigitSize: {
        fontSize: responsiveHeight(1.5),
        lineHeight: responsiveHeight(2),
        letterSpacing: responsiveWidth(0),
        color: '#383838',
    },
    widthSpace: {
        flexDirection: 'row',
        gap: responsiveWidth(2.5),
        width: responsiveWidth(69),
        justifyContent: 'space-between',
    },
    iconAndTextGap: {
        flexDirection: 'row',
        gap: responsiveWidth(2),
    },
    iconTextSpace: {
        flexDirection: 'row',
        gap: responsiveWidth(1),
    },
    bold: {
        color: '#DF09A7',
        fontSize: 16,
        fontWeight: '400',
    },
    iconMargin: { marginRight: responsiveHeight(2) },
    menuTitleContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
        paddingHorizontal: responsiveWidth(5),
    },
    menuTitleAlignment: { alignItems: 'center' },
    menuBottomBoarder: {
        borderBottomWidth: responsiveWidth(0.8),
        borderColor: '#58B9D0',
        width: '295%',
        marginLeft: responsiveWidth(2),
        top: responsiveHeight(1),
    },
    aboutText: { color: '#58B9D0', fontSize: 16, fontWeight: '600' },
    serviceText: { color: '#A1A1A1', fontSize: 16, fontWeight: '600' },
    reviewsText: { color: '#A1A1A1', fontSize: 16, fontWeight: '600' },
    bioText: {
         marginLeft: responsiveWidth(3.8) 
        },
    paragraphText: { marginHorizontal: responsiveWidth(3.5) },
    languageJobText: {
        flexDirection: 'row',
        marginLeft: responsiveWidth(3),
        gap: responsiveHeight(8),
    },
    expertiseText: { marginLeft: responsiveWidth(4) },
    setGap: {
        flexDirection: 'row',
        gap: responsiveWidth(1),
        top: responsiveHeight(0.5),
    },
    DogBorder: {
        flexDirection: 'row',
        width: responsiveWidth(21),
        height: responsiveHeight(4),
        borderWidth: 1,
        borderColor: '#D3D3D3',
        borderRadius: responsiveHeight(0.6),
        justifyContent: 'center',
        alignItems: 'center',
        gap: responsiveWidth(1),
    },
    CatBorder: {
        flexDirection: 'row',
        width: responsiveWidth(21),
        height: responsiveHeight(4),
        borderWidth: 1,
        borderColor: '#D3D3D3',
        borderRadius: responsiveHeight(0.6),
        justifyContent: 'center',
        alignItems: 'center',
        gap: responsiveWidth(1),
    },
    dogText: { color: '#4494A8', fontSize: 16, fontWeight: '600' },
    catText: { color: '#4494A8', fontSize: 16, fontWeight: '600' },
    imageContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: responsiveWidth(2),
    },
    servicetext: {
        marginLeft: responsiveWidth(3.6),
        fontSize: 18,
        fontWeight: '700',
        color: '#000000',
    },
    smallBreedContainer: {
        flexDirection: 'row',
        gap: responsiveWidth(1.5),
        marginRight: responsiveWidth(4),
    },
    TowerIconImageHeight: { top: responsiveHeight(0.4) },
    imagecontainer: { gap: responsiveHeight(1.8), bottom: responsiveHeight(1) },
    imageParent: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: responsiveWidth(4),
    },
    imageContainerRadius: {
        width: responsiveWidth(44),
        borderRadius: responsiveWidth(6),
    },
    imageRadius: {
        width: '100%',
        height: responsiveHeight(16),
        borderRadius: 10,
    },

    textIconSection: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        // marginTop: responsiveHeight(1.5),
        paddingHorizontal: responsiveWidth(2),
        paddingVertical: responsiveHeight(1),
    },
    underimageText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#000',
    },
    timeText: {
        fontSize: 10,
        color: '#A0A0A0',
        marginTop: 4,
    },
    plusCircleContainer: {
        width: responsiveWidth(7.5),
        height: responsiveHeight(3.5),
        borderRadius: responsiveWidth(10),
        backgroundColor: '#58B9D0',
        justifyContent: 'center',
        alignItems: 'center',
    },
    parentGap: { gap: responsiveWidth(3) },
    parentContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: responsiveWidth(4),
    },
    imageTextFlex: { flexDirection: 'row', gap: responsiveWidth(2) },
    dogImageSize: {
        width: responsiveWidth(12),
        height: responsiveHeight(5.5),
        borderRadius: responsiveWidth(20),
    },
    textIconHeight: { top: responsiveHeight(0.3) },
    textIconflex: { flexDirection: 'row', gap: responsiveWidth(2) },
    textsize: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#000',
    },
    DogmarkIconHeight: { top: responsiveHeight(0.5) },
    yearText: {
        fontSize: 10,
        color: '#A0A0A0',
        marginTop: 4,
    },
    center: { justifyContent: 'center', alignItems: 'center' },
    button: {
        width: responsiveWidth(95),
        height: responsiveHeight(5.4),
        borderRadius: responsiveHeight(0.9),
        backgroundColor: '#58B9D0',
        justifyContent: 'center',
        alignItems: 'center',
    },
    ContinueText: { color: '#FFFFFF', fontSize: 14, fontWeight: '600' },
});

export default groomingaboutstyles;
