import { StatusBar, StyleSheet } from 'react-native';
import {
  responsiveHeight,
  responsiveWidth,
  responsiveFontSize,
} from 'react-native-responsive-dimensions';

const settlementCheckoutStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9FAFB',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: responsiveWidth(5),
    paddingVertical: responsiveHeight(2),
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    paddingTop: StatusBar.currentHeight,
  },
  headerTitle: {
    fontSize: responsiveFontSize(2.2),
    fontWeight: '700',
    color: '#111827',
  },
  headerSubtitle: {
    fontSize: responsiveFontSize(1.6),
    color: '#6B7280',
    marginTop: 2,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#F3F4F6',
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  cardTitle: {
    fontSize: responsiveFontSize(2),
    fontWeight: '700',
    color: '#111827',
    marginLeft: 10,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
  },
  infoLabel: {
    fontSize: responsiveFontSize(1.8),
    color: '#6B7280',
    fontWeight: '500',
  },
  infoValue: {
    fontSize: responsiveFontSize(1.8),
    color: '#111827',
    fontWeight: '600',
    flex: 1,
    textAlign: 'right',
  },
  serviceBreakdownRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  serviceIconBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  serviceBreakdownLabel: {
    flex: 1,
    fontSize: responsiveFontSize(1.8),
    color: '#374151',
    fontWeight: '500',
  },
  serviceBreakdownAmount: {
    fontSize: responsiveFontSize(1.9),
    color: '#111827',
    fontWeight: '700',
  },
  grandTotalCard: {
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
  },
  grandTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  grandTotalLabel: {
    fontSize: responsiveFontSize(1.6),
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 1.2,
  },
  grandTotalValue: {
    fontSize: responsiveFontSize(3.2),
    fontWeight: '800',
    color: '#FFFFFF',
  },
  noteCard: {
    backgroundColor: '#FFFBEB',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#FDE68A',
  },
  noteIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FEF3C7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  noteTitle: {
    fontSize: responsiveFontSize(1.8),
    fontWeight: '700',
    color: '#92400E',
    marginBottom: 4,
  },
  noteText: {
    fontSize: responsiveFontSize(1.6),
    color: '#78350F',
    lineHeight: 20,
  },
  bottomSection: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: responsiveWidth(5),
    paddingVertical: responsiveHeight(2),
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
  },
  confirmButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: responsiveHeight(2),
    borderRadius: 12,
    gap: 10,
  },
  confirmButtonText: {
    fontSize: responsiveFontSize(2),
    fontWeight: '700',
    color: '#FFFFFF',
  },
});

export default settlementCheckoutStyles;
