
const images = {
    Walking: require('./Walking.png'),
    serviceveterinaryImage: require('./ServiceImage.webp'),
    Boarding: require('./Boarding.png'),
    Training: require('./Training.png'),
    ParaVet: require('./paraVetImage.webp'),
    NGOs: require('./NGOs.png'),
    FirstGrooming:require('./FirstGrooming.jpg'),
    SecondGrooming:require('./SecondGrooming.jpg'),
    UserImage:require('./userImage.png'),
    DogServiceImage:require('./dogServiceImage.jpg'),
    HairCutDog:require('./HairCutDog.png'),
    germanDog:require('./germanDog.jpg'),
    goldenDog:require('./goldenDog.jpg'),
    spaneilDog:require('./spaneilDog.jpg'),
    HairStyle: require('./HairCutStyle.png'),
    washDogImage:require('./washDogImage.jpg'),
    happycartoonDog: require('./happyCartoonDog.png'),
    happywalkingwithDog:require('./firsthappyimage.webp'),
    happywalkingmanwithDog:require('./secondhappyimage.webp'),
    walkinguserimage:require('./walkinguserimage.webp'),
    paravetUserImage:require('./paravetUserImage.webp'),
    firstwalker:require('./firstwalker.webp'),
    secondwalker:require('./secondwalker.webp'),
    thirdwalker:require('./thirdwalker.webp'),
    petdogImage:require('./petdogImage.webp'),
    firstGradleImage:require('./firstGradleImage.webp'),
    secondGradleImage:require('./secondGradleImage.webp'),
    thirdGradleImage:require('./thirdGradleImage.webp'),
    BellaDog:require('./BellaDog.webp'),
    DaisyDog:require('./DaisyDog.webp'),
    silentDog:require('./silentDog.webp'),
    catwashImage:require('./catwashImage.webp'),
    packageImage:require('./packageImage.webp'),
    trainingDog:require('./trainingDog.webp'),
    userparavetImage:require('./userparavet.webp'),
    petjioLogo:require('./petjioLogo.webp'),
    signupImage:require('./signupImage.webp'),
    petparent:require('./petparent.webp'),
    petwarrior:require('./petwarrior.webp'),
    serviceprovider:require('./serviceprovider.webp'),
    deliverypartner:require('./deliverypartner.webp'),
    veterinary:require('./veterinary.webp'),
    grooming:require('./grooming.webp'),
    GroomingService:require('./GroomingService.webp'),
    trainer:require('./trainer.webp'),
    dogwalking:require('./dogwalking.webp'),
    petsitter:require('./petsitter.webp'),
    transport:require('./transport.webp'),
    paraverservice:require('./paraverservice.webp'),
    ngoconnect:require('./ngoconnect.webp'),
    boardingservice:require('./boardingservice.webp'),
    petmart:require('./petmart.webp'),
    breeder:require('./breeder.webp'),
    laboratory:require('./laboratory.webp'),
    signinImage:require('./longin.webp'),
    googleMap:require('./googleMap.webp'),
    injection:require('./injection.webp'),
    amc_Icon:require('./amc_Icon.webp'),
    veterinariTakingImage:require('./veterinariTakingImage.webp'),
    petconimage:require('./petconimage.webp'),
    ngoImage:require('./ngoImage.webp'),
    petLogoImage:require('./petLogoImage.webp'),
    straypetImage:require('./straypetImage.webp'),
    petLogoFrame:require('./petLogoFrame.webp'),
    adoptionImage:require('./adoptionImage.webp'),
    animalRescueImage:require('./animalRescueImage.webp'),
    tacticalResecueImage:require('./tacticalResecueImage.webp'),
    humanedImage:require('./humanedImage.webp'),
    dogRestHouseImage:require('./dogRestHouseImage.webp'),
    rabieshelpline:require('./rabieshelpline.webp'),
    dogWithPeopleImage:require('./dogWithPeopleImage.webp'),
    physicaladoptionImage:require('./physicaladoptionImage.webp'),
    virtualadoptionImage:require('./virtualadoptionImage.webp'),
    anascaledImage:require('./anascaledImage.webp'),
    foodbowlsImage:require('./foodbowlsImage.webp'),
    makedonationImage:require('./makedonationImage.webp'),
    donatecareImage:require('./donatecareImage.webp'),
    catcareImage:require('./catcareImage.webp'),
    fluidscalmImage:require('./fluidscalmImage.webp'),
    veterinaryInjectionImage:require('./veterinaryInjectionImage.webp'),
    glandcleaningImage:require('./glandcleaningImage.webp'),
    bloodtestImage:require('./bloodtestImage.webp'),
    gettyImages:require('./gettyImages.webp'),
    indiandogImage:require('./indiandogImage.webp'),
    villagedogImage:require('./villagedogImage.webp'),
    towndogImage:require('./towndogImage.webp'),
    shepherdogImage:require('./shepherdogImage.webp'),
    cbcImage:require('./cbcImage.webp'),
    buntestImage:require('./buntestImage.webp'),
    bloodtestforDogImage:require('./bloodtestforDogImage.webp'),
    dogheroImage:require('./dogheroImage.webp'),
    shullterstockImage:require('./shullterstockImage.webp'),
    tribulindogImage:require('./tribulindogImage.webp'),
    ThyroidpanelImage:require('./ThyroidpanelImage.webp'),
    shullterStockDogImage:require('./shullterStockDogImage.webp'),
    HeartwormbloodTestImage:require('./HeartwormbloodTestImage.webp'),
    pregmentImage:require('./pregmentImage.webp'),
    nailclippingImage:require('./nailclippingImage.webp'),
    bathingImage:require('./bathingImage.webp'),
    furbrushingImage:require('./furbrushingImage.webp'),
    spabathImage:require('./spabathImage.webp'),
    istockImage:require('./istockImage.webp'),
    pethealthImage:require('./pethealthImage.webp'),
    dogcollarImage:require('./dogcollarImage.webp'),
    premiumdogcollorImage:require('./premiumdogcollorImage.webp'),
    groomerImage:require('./groomerImage.webp'),
    dogmouthImage:require('./dogmouthImage.webp'),
    wetfoodImage:require('./wetfoodImage.webp'),
    dryfoodImage:require('./dryfoodImage.webp'),
    treatsImage:require('./treatsImage.webp'),
    toysImage:require('./toysImage.webp'),
    collorharnessImage:require('./collorharnessImage.webp'),
    bowlsImage:require('./bowlsImage.webp'),
    litterboxImage:require('./litterboxImage.webp'),
    grearImage:require('./grearImage.webp'),
    groomingtoolImage:require('./groomingtoolImage.webp'),
    petfurnitureImage:require('./petfurnitureImage.webp'),
    vitaminsImage:require('./vitaminsImage.webp'),
    equipmentImage:require('./equipmentImage.webp'),
    cookedfoodImage:require('./cookedfoodImage.webp'),
    treatstorageImage:require('./treatstorageImage.webp'),
    tongImage:require('./tongImage.webp'),
    tongbackwordImage:require('./tongbackwordImage.webp'),
    tonghorizontalImage:require('./tonghorizontalImage.webp'),
    dogteethImage:require('./dogteethImage.webp'),
    petjiostoreImage:require('./petjiostoreImage.webp'),
    dumbellImage:require('./dumbellImage.webp'),
    ropedogImage:require('./ropedogImage.webp'),
    petJiocrecheImage:require('./petJiocrecheImage.webp'),
    adulttrainingImage:require('./adulttrainingImage.webp'),
    petjioclinicImage:require('./petjioclinicImage.webp'),
    doctorImage:require('./doctorImage.webp'),
    veterinaryImage:require('./veterinaryImage.webp'),
    patientImage:require('./patientImage.webp'),
    goldenRetriver:require('./goldenRetriver.webp'),
    userShowImage:require('./userShowImage.webp'),
    pharmacyImage:require('./pharmacyImage.webp'),
    syrupImage:require('./syrupImage.webp'),
    deliverymanImage:require('./deliverymanImage.webp'),
    
  
   
};

export default images;