import { StyleSheet } from 'react-native';
import {
    responsiveWidth,
    responsiveHeight,
} from 'react-native-responsive-dimensions';
const InvoiceDetailstyles = StyleSheet.create({
    container: {
        width: responsiveWidth(100),
        height: responsiveHeight(100),
        backgroundColor: '#FFFFFF',
    },
    containerchild: {
        width: responsiveWidth(100),
        padding: responsiveWidth(4),
        flexDirection: 'row',
        justifyContent: 'space-between',
        top: responsiveHeight(4),
        paddingHorizontal: responsiveHeight(2.5),
    },
    containerfirstsubchild: {
        flexDirection: 'row',
        gap: responsiveWidth(2.1),
    },
    downArrowIcon: {
        tintColor: '#000000',
        top: responsiveHeight(0.25),
    },
    leftarrowicon: {
        tintColor: '#000000',
        top: responsiveHeight(0.5),
    },
    checkoutText: {
        fontSize: 18,
        fontWeight: '600',
        lineHeight: 17,
        color: '#000000',
        top: responsiveHeight(1),
    },
    congratualtiondetailsView: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    congratualtiondetails: {
        gap: responsiveHeight(3),
        width: responsiveWidth(90),
        height: responsiveHeight(24),
        color: '#FFFFFF',
        shadowColor: '#A1A1A1',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.9,
        shadowRadius: 4,
        elevation: 5,
        top: responsiveHeight(5.5),
        borderRadius: responsiveWidth(0.5),
    },
    congratulationText: {
        fontSize: 16,
        fontWeight: '600',
        lineHeight: 18,
        letterSpacing: 0,
        color: '#000000',
    },
    row: {
        flexDirection: 'row',
        top: responsiveHeight(2.2),
        margin: responsiveHeight(0.9),
    },
    bookedText: {
        fontSize: 12,
        fontWeight: '500',
        color: '#555555',
        lineHeight: 17,
    },
    BookingID: {
        fontSize: 14,
        fontWeight: '600',
        lineHeight: 17,
        letterSpacing: 0,
        color: '#000000',
    },
    TPNumber: { fontSize: 12, fontWeight: '400', color: '#555555' },
    PAIDTEXT: { fontSize: 12, fontWeight: '400', color: '#FFFFFF' },
    TotalAmount: {
        fontSize: 16,
        fontWeight: '600',
        lineHeight: 17,
        letterSpacing: 0,
        color: '#DF09A7',
    },
    IDTPNRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: responsiveWidth(5),
    },
    petdetailsText: {
        fontSize: 16,
        fontWeight: '600',
        lineHeight: 18,
        letterSpacing: 0,
        color: '#000000',
        left: responsiveWidth(2),
    },
    viewGap: { gap: responsiveHeight(1) },
    petdetailsview: {
        gap: responsiveHeight(3),
        width: responsiveWidth(90),
        height: responsiveHeight(23),
        color: '#FFFFFF',
        shadowColor: '#A1A1A1',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.9,
        shadowRadius: 4,
        elevation: 5,
        borderRadius: responsiveWidth(0.5),
    },
    petdetailsviewGap: {
        top: responsiveHeight(4),
        paddingHorizontal: responsiveHeight(0.4),
        gap: responsiveHeight(1),
    },
    // Fixed Button
    fixedButtonContainer: {
        position: 'absolute',
        bottom: 0,
        width: '100%',
        backgroundColor: 'white',
        paddingVertical: responsiveHeight(2),
        alignItems: 'center',
    },
    nextBtnContainer: {
        justifyContent: 'center',
        alignItems: 'center',
        width: responsiveWidth(92),
        height: responsiveHeight(5),
        borderRadius: responsiveHeight(0.8),
        backgroundColor: '#58B9D0',
    },
    nextBtnText: {
        fontSize: 16,
        fontWeight: '400',
        color: '#FFFFFF',
    },
});

export default InvoiceDetailstyles;
