import { StyleSheet, Platform } from 'react-native';
import {
    responsiveWidth,
    responsiveHeight,
} from 'react-native-responsive-dimensions';

const boardingQuestionStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8F9FB',
    },
    // Header styles matching BoardingCheckout
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingTop: Platform.OS === 'ios' ? 60 : 40,
        paddingBottom: 12,
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1A1D29',
    },
    headerSubtitle: {
        fontSize: 13,
        color: '#6B7280',
        marginTop: 2,
    },
    containerchild: {
        width: responsiveWidth(100),
        paddingVertical: responsiveHeight(2),
        paddingHorizontal: responsiveWidth(4),
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'center',
        marginTop: responsiveHeight(3),
        marginBottom: responsiveHeight(1),
        backgroundColor: '#FFFFFF',
    },
    containerfirstsubchild: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: responsiveWidth(2)
    },
    leftarrowicon: {
        tintColor: '#000000',
        width: 20,
        height: 20,
    },
    groomingText: {
        color: '#000000',
        fontSize: 18,
        fontWeight: '600',
        fontFamily: '',
    },
    scrollContainer: {
        flex: 1,
        paddingHorizontal: responsiveWidth(5),
    },
    formSection: {
        marginBottom: responsiveHeight(3),
    },
    subtitle: {
        fontSize: 16,
        color: '#666666',
        textAlign: 'center',
        lineHeight: 22,
    },
    questionsContainer: {
        gap: responsiveHeight(1.5),
        marginBottom: responsiveHeight(4),
        paddingHorizontal: responsiveWidth(1),
    },
    questionCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: responsiveWidth(4),
        borderWidth: 1,
        borderColor: '#E5E7EB',
        marginBottom: responsiveHeight(1),
    },
    questionHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: responsiveHeight(1.5),
        gap: responsiveWidth(3),
    },
    iconContainer: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: 'rgba(88, 185, 208, 0.1)',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 2,
    },
    questionInfo: {
        flex: 1,
    },
    questionNumber: {
        fontSize: 12,
        fontWeight: '600',
        color: '#58B9D0',
        marginBottom: responsiveHeight(0.5),
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    questionText: {
        fontSize: 14,
        fontWeight: '400',
        color: '#4B5563',
        lineHeight: 20,
    },
    answerButtons: {
        flexDirection: 'row',
        gap: responsiveWidth(2),
        marginTop: responsiveHeight(1.5),
    },
    answerButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: responsiveHeight(1.2),
        paddingHorizontal: responsiveWidth(3),
        borderRadius: 8,
        borderWidth: 1.5,
        borderColor: '#E5E7EB',
        backgroundColor: '#F9FAFB',
        gap: responsiveWidth(1.5),
    },
    selectedYes: {
        backgroundColor: '#F0FDF4',
        borderColor: '#10B981',
    },
    selectedNo: {
        backgroundColor: '#FEF2F2',
        borderColor: '#EF4444',
    },
    answerText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#6B7280',
    },
    selectedYesText: {
        color: '#10B981',
        fontWeight: '600',
    },
    selectedNoText: {
        color: '#EF4444',
        fontWeight: '600',
    },
    bookButton: {
        backgroundColor: '#58B9D0',
        paddingVertical: responsiveHeight(1.8),
        paddingHorizontal: responsiveWidth(4),
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
        marginTop: responsiveHeight(2),
        marginBottom: responsiveHeight(3),
        width: responsiveWidth(90),
    },
    disabledButton: {
        backgroundColor: '#CCCCCC',
    },
    bookButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#FFFFFF',
    },
    // Error Modal Styles
    errorModalOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    errorModalContainer: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: responsiveWidth(6),
        width: responsiveWidth(85),
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    errorTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#F44336',
        marginBottom: responsiveHeight(2),
    },
    errorMessage: {
        fontSize: 16,
        color: '#333333',
        textAlign: 'center',
        lineHeight: 22,
        marginBottom: responsiveHeight(3),
    },
    errorButton: {
        backgroundColor: '#58B9D0',
        paddingVertical: responsiveHeight(1.5),
        paddingHorizontal: responsiveWidth(8),
        borderRadius: 8,
    },
    errorButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#FFFFFF',
    },
    // Form Elements
    sectionTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#111827',
        marginBottom: responsiveHeight(1.5),
        marginTop: responsiveHeight(2),
    },
    dropdownContainer: {
        marginBottom: responsiveHeight(2),
    },
    dropdown: {
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#D1D5DB',
        borderRadius: 8,
        paddingVertical: responsiveHeight(1.5),
        paddingHorizontal: responsiveWidth(4),
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    dropdownText: {
        fontSize: 14,
        color: '#374151',
    },
    dropdownPlaceholder: {
        fontSize: 14,
        color: '#9CA3AF',
    },
    dropdownOptions: {
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#D1D5DB',
        borderRadius: 8,
        marginTop: responsiveHeight(0.5),
        maxHeight: responsiveHeight(25),
    },
    dropdownOption: {
        paddingVertical: responsiveHeight(1.5),
        paddingHorizontal: responsiveWidth(4),
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
    },
    dropdownOptionLast: {
        borderBottomWidth: 0,
    },
    dropdownOptionText: {
        fontSize: 14,
        color: '#374151',
    },
    selectedOption: {
        backgroundColor: '#F0F9FF',
    },
    selectedOptionText: {
        color: '#0284C7',
        fontWeight: '500',
    },
    // Service Items
    serviceItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 8,
        paddingVertical: responsiveHeight(1.5),
        paddingHorizontal: responsiveWidth(4),
        marginBottom: responsiveHeight(1),
    },
    serviceItemSelected: {
        backgroundColor: '#F0F9FF',
        borderColor: '#0284C7',
    },
    serviceLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        gap: responsiveWidth(3),
    },
    serviceIcon: {
        width: 24,
        height: 24,
    },
    serviceInfo: {
        flex: 1,
    },
    serviceName: {
        fontSize: 14,
        fontWeight: '500',
        color: '#111827',
    },
    servicePrice: {
        fontSize: 12,
        color: '#6B7280',
        marginTop: 2,
    },
    checkbox: {
        width: 24,
        height: 24,
        borderRadius: 4,
        borderWidth: 2,
        borderColor: '#D1D5DB',
        backgroundColor: '#FFFFFF',
        justifyContent: 'center',
        alignItems: 'center',
    },
    checkboxSelected: {
        backgroundColor: '#0284C7',
        borderColor: '#0284C7',
    },
    checkIcon: {
        width: 14,
        height: 14,
        tintColor: '#FFFFFF',
    },
    // Walks Counter
    walksContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 8,
        paddingVertical: responsiveHeight(1.5),
        paddingHorizontal: responsiveWidth(4),
        marginBottom: responsiveHeight(1.5),
    },
    walksLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: responsiveWidth(3),
    },
    walksText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#111827',
    },
    walksCounter: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: responsiveWidth(3),
    },
    walksButton: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#F3F4F6',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#D1D5DB',
    },
    walksButtonDisabled: {
        opacity: 0.4,
    },
    walksButtonIcon: {
        width: 18,
        height: 18,
        tintColor: '#374151',
    },
    walksValue: {
        fontSize: 16,
        fontWeight: '600',
        color: '#111827',
        minWidth: 30,
        textAlign: 'center',
    },
    // Pet Navigation
    petIndicator: {
        fontSize: 14,
        color: '#6B7280',
        marginTop: 4,
    },
    nextButton: {
        backgroundColor: '#0284C7',
        paddingVertical: responsiveHeight(1.8),
        borderRadius: 8,
        alignItems: 'center',
        marginHorizontal: responsiveWidth(5),
        marginVertical: responsiveHeight(2),
    },
    nextButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#FFFFFF',
    },
});

export default boardingQuestionStyles;