export default {
    Home: require('./Home.png'),
    Profile: require('./Profile.png'),
    Mart: require('./Mart.png'),
    Visits: require('./Visits.png'),
    Service: require('./Service.png'),
    Filter: require('./Filter.png'),
    LeftArrow: require('./BiLeftArrowAlt.png'),
    DownArrow: require('./RiArrowDropDownLine.png'),
    Calendar: require('./BiCalendar.png'),
    Scissors: require('./BsScissors.png'),
    HomeHeart: require('./BiHomeHeart.png'),
    Check: require('./BiCheck.png'),
    ClockCircle: require('./AiOutlineClockCircle.png'),
    locationIcon: require('./LocationIcon.png'),
    Vector: require('./Vector.png'),
    Location: require('./Location.png'),
    StarIcon: require('./StarIcon.png'),
    LoveIcon:require('./LoveIcon.png'),
    LuDog:require('./LuDog.png'),
    LuCat:require('./LuCat.png'),
    TowerIcon:require('./TowerIcon.png'),
    DogmarkIcon:require('./DogmarkIcon.png'),
    Ellipse:require('./Ellipse.png'),
    alertEllipse:require('./alertEllipse.png'),
    locationposition:require('./locationposition.png'),
    BiCalendar:require('./BiCalendar.png'),
    pathNewIcon:require('./mask_group.png'),
    newpathIcon:require('./nailclipping.png'),
    IoIosArrowUp:require('./IoIosArrowUp.png'),
    IoIosArrowForward:require('./IoIosArrowForward.png'),
    petjioIcon:require('./petjioIcon.png'),
    visa:require('./visa.png'),
    googlepay:require('./google_pay.png'),
    upi:require('./upi.png'),
    card:require('./card.png'),
    phonepay:require('./phonepay.png'),
    paytm:require('./paytm.png'),
    BiAlarmExclamation:require('./BiAlarmExclamation.png'),
    happyparty:require('./happyparty.png'),
    search:require('./search.png'),
    BiBell:require('./BiBell.png'),
    BiTimeFive:require('./BiTimeFive.png'),
    MdVerifiedUser:require('./MdVerifiedUser.png'),
    BlackBiCalendar:require('./BlackBiCalendar.png'),
    BiPlus:require('./BiPlus.png'),
    BiMap:require('./BiMap.png'),
    IoMdPaw:require('./IoMdPaw.png'),
    earthIcon:require('./earthIcon.png'),
    IoIosArrowBack:require('./IoIosArrowBack.png'),
    IoIosArrowForwardWhite:require('./IoIosArrowForwardWhite.png'),
    WhiteBiCalendar:require('./WhiteBiCalendar.png'),
    BiSolidHourglass:require('./BiSolidHourglass.png'),
    TbCoinRupee:require('./TbCoinRupee.png'),
    BiFemaleSign:require('./BiFemaleSign.png'),
    BiSolidCheckCircle:require('./BiSolidCheckCircle.png'),
    CgRadioCheck:require('./CgRadioCheck.png'),
    BiMaleSign:require('./BiMaleSign.png'),
    ForwardArrow:require('./ForwardArrow.png'),
    BiMessageSquareDetail:require('./BiMessageSquareDetail.png'),
    MdOutlineCall:require('./MdOutlineCall.png'),
    RiPinDistanceLine:require('./RiPinDistanceLine.png'),
    PiBuildingApartment:require('./PiBuildingApartment.png'),
    IoLogoNoSmoking:require('./IoLogoNoSmoking.png'),
    MdChildCare:require('./MdChildCare.png'),
    meals:require('./meals.png'),
    Care:require('./Care.png'),
    Outside:require('./Outside.png'),
    googleIcon:require('./googleIcon.png'),
    facebookIcon:require('./facebookIcon.png'),
    eyeInvisible:require('./AiOutlineEyeInvisible.png'),
    BiPhone:require('./BiPhone.png'),
    WhiteBiPhone:require('./WhiteBiPhone.png'),
    BiMessageSquareDetails:require('./BiMessageSquareDetails.png'),
    WhiteMdFavoriteBorder:require('./WhiteMdFavoriteBorder.png'),
    playIcon:require('./playIcon.png'),
    dotIcon:require('./dotIcon.png'),
    WhiteBiPlusIcon:require('./WhiteBiPlusIcon.png'),
    RiDeleteBinLine:require('./RiDeleteBinLine.png'),
    EllipseIcon:require('./EllipseIcon.png'),
    bloodconectionIcon:require('./bloodconectionIcon.png'),
    bloodIsonthWayIcon:require('./bloodIsonthWayIcon.png'),
    BsTelephone:require('./BsTelephone.png'),
    catfoodIcon:require('./catfoodIcon.png'),
    pethampooIcon:require('./pethampooIcon.png'),
    WishlisIcon:require('./WishlisIcon.png'),
    pethealthIcon:require('./pethealthIcon.png'),
    AiFillStar:require('./AiFillStar.png'),
    BiDownArrowAlt:require('./BiDownArrowAlt.png'),
    BiShoppingBag:require('./BiShoppingBag.png'),
    BiCart:require('./BiCart.png'),
    catIcon:require('./catIcon.png'),
    clownfishIcon:require('./clownfishIcon.png'),
    doglegIcon:require('./doglegIcon.png'),
    playBtn:require('./playBtn.png'),
    fourateloveIcon:require('./fourateloveIcon.png'),
    autocartIcon:require('./autocartIcon.png'),
    YelloAiFillStar:require('./YelloAiFillStar.png'),
    BsTelephoneFill:require('./BsTelephoneFill.png'),
    BiSolidMessageSquareDots:require('./BiSolidMessageSquareDots.png'),
    grayWhiteIcon:require('./grayWhiteIcon.png'),
    yellowIcon:require('./yellowIcon.png'),
    redIcon:require('./redIcon.png'),
    blueIcon:require('./blueIcon.png'),
    BiMinus:require('./BiMinus.png'),
    MdDelete:require('./MdDelete.png'),
    petcoinIcon:require('./petcoinIcon.png'),
    wallet:require('./wallet.png'),
    BiBriefcase:require('./BiBriefcase.png'),
    BiMessageSquareDots:require('./BiMessageSquareDots.png'),
    AiOutlineStar:require('./AiOutlineStar.png'),
    BiSolidCamera:require('./BiSolidCamera.png'),
    BsFillCameraVideoFill:require('./BsFillCameraVideoFill.png'),
    petjio_logo:require('./petjio_logo.png'),
    BsFillTelephoneFill:require('./BsFillTelephoneFill.png'),
    BsFillTelephoneXFill:require('./BsFillTelephoneXFill.png'),
    CgAttachment:require('./CgAttachment.png'),
    BiCamera:require('./BiCamera.png'),
    BiSolidFilePng:require('./BiSolidFilePng.png'),
    PiShareFat:require('./PiShareFat.png'),
    BsCameraVideoFill:require('./BsCameraVideoFill.png'),
    BsChatDotsFill:require('./BsChatDotsFill.png'),
    BsFillMicFill:require('./BsFillMicFill.png'),
    BiSolidPhone:require('./BiSolidPhone.png'),
    CgRadioChecked:require('./CgRadioChecked.png'),
    BiSolidPhoneCall:require('./BiSolidPhoneCall.png'),
    CashIcon:require('./CashIcon.png'),
    


    
    
    

};
